name: End-to-End Test LabLink Client VM Infrastructure

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "packages/allocator/tests/terraform/**"
      - "lablink-infrastructure/**"
      - ".github/workflows/client-vm-infrastructure-test.yml"

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test LabLink Client VM Infrastructure
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'us-west-2' }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: packages/allocator
        run: |
          uv sync --all-extras

      - name: Remove backend config
        run: |
          rm -f packages/allocator/src/lablink_allocator/terraform/backend.tf

      - name: Run tests
        working-directory: packages/allocator/tests/terraform
        run: |
          uv run pytest tests --maxfail=1 --disable-warnings
